[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "12.22.12"  # Required for sharp compatibility
  PYTHON_VERSION = "3.8.20"  # Required for sharp compatibility 
